// <auto-generated />
namespace AsusLaptop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class product_isnew_cilumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(product_isnew_cilumn));
        
        string IMigrationMetadata.Id
        {
            get { return "201905130622030_product_isnew_cilumn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
